version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: scripts/backup.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/rsync_deploy.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/restart_backend.sh
      timeout: 300
      runas: root

