import { Router } from 'express';
import authRoutes from './auth.route.js';
import masterRoutes from './master.route.js';
import creditTenantRoutes from './creditTenant.route.js';
import superadminRoutes from './superadmin.route.js';
import stationRoutes from './station.route.js';
import productRoutes from './product.route.js';
import staffshiftRoutes from './staffshift.route.js';
import operationsRoutes from './operations.route.js';
import transactionRoutes from './transaction.route.js';
import decantationLogsRoutes from './decantationLogs.route.js';
import salesRoutes from './sales.route.js';
import purchaseRoutes from './purchase.route.js';
import ledgerRoutes from './ledger.route.js';
const router = Router();

router.use('/auth', authRoutes);
router.use('/master', masterRoutes);
router.use('/tenant', creditTenantRoutes);
router.use('/superadmin', superadminRoutes);
router.use('/tenant', stationRoutes);
router.use('/tenant', productRoutes);
router.use('/tenant', staffshiftRoutes);
router.use('/tenant', operationsRoutes);
router.use('/tenant', transactionRoutes);
router.use('/tenant', decantationLogsRoutes);
router.use('/tenant/sales', salesRoutes);
router.use('/tenant', purchaseRoutes);
router.use('/tenant/ledger', ledgerRoutes);

export default router;